version: '3.1'

services:
    phpapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8892:80
        # links:
        #     - phpapi:phpapi
        # volumes:
        #   - ./src:/var/www/html/

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: fakeStore
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - 8088:80
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
